# Generated by Django 4.2.15 on 2024-08-13 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='buy_time',
        ),
        migrations.RemoveField(
            model_name='car',
            name='buyer',
        ),
    ]
